GET http://localhost:3000/api/hello-world

###

POST http://localhost:3000/api/coffees
Content-Type: application/json

{
    "name": "mock-coffee",
    "brand": "mock-brand",
    "recommendations": 0,
    "flavors": []
}

###

GET http://localhost:3000/api/coffees

###

POST http://localhost:3000/api/events
Content-Type: application/json

{
    "type": "mock-type",
    "name": "mock-name",
    "payload": { "mock": "payload" }
}

###

GET http://localhost:3000/api/events
